# Generated by Django 4.2.3 on 2023-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_alter_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_mail',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_sms',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
